### ISSUE TITLE
AttributeError: 'sapien.core.pysapien.VulkanScene' object has no attribute 'set_ambient_light'

### ISSUE THREAD

**Issue by samo133** [haosulab/ManiSkill-Learn#30]
when I run the following example 
python -m tools.run_rl configs/bc/mani_skill_point_cloud_transformer.py \
--gpu-ids=0 --cfg-options "env_cfg.env_name=OpenCabinetDrawer_1045_link_0-v0" \
"eval_cfg.save_video=True" "eval_cfg.num=10" "eval_cfg.use_log=True" \
--work-dir=./test/OpenCabinetDrawer_1045_link_0-v0_pcd \
--resume-from=./example_mani_skill_data/OpenCabinetDrawer_1045_link_0-v0_PN_Transformer.ckpt --evaluation

I got this error
opencv-contrib not installed, some features will be disabled.
Please install with `pip3 install opencv-contrib-python`
INFO - 2022-08-24 15:26:27,224 - utils - Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
Traceback (most recent call last):
  File "/home/osama/anaconda3/envs/mani_skill/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/osama/anaconda3/envs/mani_skill/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/osama/Desktop/RI/ManiSkill/ManiSkill-Learn/tools/run_rl.py", line 265, in <module>
    main()
  File "/home/osama/Desktop/RI/ManiSkill/ManiSkill-Learn/tools/run_rl.py", line 154, in main
    evaluator = build_evaluation(eval_cfg)
  File "/home/osama/Desktop/RI/ManiSkill/ManiSkill-Learn/mani_skill_learn/env/builder.py", line 32, in build_evaluation
    return build_from_cfg(cfg, EVALUATIONS, default_args)
  File "/home/osama/Desktop/RI/ManiSkill/ManiSkill-Learn/mani_skill_learn/utils/meta/registry.py", line 132, in build_from_cfg
    return obj_cls(**args)
  File "/home/osama/Desktop/RI/ManiSkill/ManiSkill-Learn/mani_skill_learn/env/evaluation.py", line 36, in __init__
    self.env = build_env(env_cfg)
  File "/home/osama/Desktop/RI/ManiSkill/ManiSkill-Learn/mani_skill_learn/env/env_utils.py", line 95, in build_env
    return build_from_cfg(cfg, ENVS, default_args)
  File "/home/osama/Desktop/RI/ManiSkill/ManiSkill-Learn/mani_skill_learn/utils/meta/registry.py", line 132, in build_from_cfg
    return obj_cls(**args)
  File "/home/osama/Desktop/RI/ManiSkill/ManiSkill-Learn/mani_skill_learn/env/env_utils.py", line 60, in make_gym_env
    env = gym.make(env_name, **tmp_kwargs)
  File "/home/osama/anaconda3/envs/mani_skill/lib/python3.8/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/osama/anaconda3/envs/mani_skill/lib/python3.8/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/home/osama/anaconda3/envs/mani_skill/lib/python3.8/site-packages/gym/envs/registration.py", line 60, in make
    env = cls(**_kwargs)
  File "/home/osama/Desktop/RI/ManiSkill/mani_skill/env/open_cabinet_door_drawer.py", line 364, in __init__
    super().__init__(
  File "/home/osama/Desktop/RI/ManiSkill/mani_skill/env/open_cabinet_door_drawer.py", line 27, in __init__
    super().__init__(
  File "/home/osama/Desktop/RI/ManiSkill/mani_skill/env/base_env.py", line 93, in __init__
    obs = self.reset(level=0)
  File "/home/osama/Desktop/RI/ManiSkill/mani_skill/env/open_cabinet_door_drawer.py", line 39, in reset
    super().reset(*args, **kwargs)
  File "/home/osama/Desktop/RI/ManiSkill/mani_skill/env/base_env.py", line 160, in reset
    self._setup_renderer()
  File "/home/osama/Desktop/RI/ManiSkill/mani_skill/env/base_env.py", line 188, in _setup_renderer
    self._scene.renderer_scene.set_ambient_light(
AttributeError: 'sapien.core.pysapien.VulkanScene' object has no attribute 'set_ambient_light'

Note that opencv-contrib-python is installed.

**Comment by xuanlinli17** [comment]
What is your SAPIEN version?
`pip show sapien`

**Comment by samo133** [comment]
Version: 2.1.0

**Comment by xuanlinli17** [comment]
Could you try to install sapien 1.1.1?
2.x has major updates and will not work for ManiSkill1 (it's supported for ManiSkill2)
`https://pypi.org/project/sapien/#history`

**Comment by samo133** [comment]
It works with sapien 1.1.1.
Thank you so much
